ledger/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView

urlpatterns = [
    path('recipes/list/', RecipeListView.as_view(), name='recipe_list'),
    path('recipes/<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
]

app_name = "ledger"

recipebook/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ledger.urls', namespace="ledger")),
    path('accounts/', include('django.contrib.auth.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    user_bio = models.TextField()
    
    def __str__(self):
        return self.name

# Create your models here.

ledger/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Ingredient(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(self.name, args=[str(self.name)])

class Recipe(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author',
        null=True
    )
    created_on = models.DateField(
        auto_now_add=True,
        null=True)
    updated_on = models.DateField(
        auto_now=True,
        null=True)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(self.name, args=[str(self.name)])
    
class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=50)
    ingredient = models.ForeignKey(
        Ingredient, 
        on_delete=models.CASCADE,
        related_name = 'recipe'
    )
    recipe = models.ForeignKey(
        Recipe, 
        on_delete=models.CASCADE,
        related_name = 'ingredients'
    )
    
    def __str__(self):
        return f"{self.recipe}: {self.quantity} of {self.ingredient}"
        
    def get_absolute_url(self):
        return reverse(self.name, args=[str(self.name)])

accounts/views.py
from django.shortcuts import render

# Create your views here.

ledger/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Recipe

class RecipeListView(ListView):
    model = Recipe
    template_name = 'ledger/recipe_list.html'
    context_object_name = 'recipes'
    
class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'ledger/recipe_detail.html'
    context_object_name = 'recipe'
    redirect_field_name = '/accounts/login'
    

ledger/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}Recipe Book{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Recipe Book</h1>
        {% if user.is_authenticated %}
			<form method="POST" action="{% url 'logout' %}">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit">Logout</button>
			</form>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

ledger/templates/ledger/recipe_detail.html
<!-- templates/ledger/recipe_detail.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ recipe.name }}{% endblock %}
{% block content %}
    <h2>{{ recipe.name }}</h2>
    <ul>
        <li>Written by {{ recipe.author }}</li>
        <li>Created on {{ recipe.created_on }}</li>
        <li>Last updated on {{ recipe.updated_on }}</li>
    </ul>
    <h3>Ingredients:</h3>
    <ul>
        {% for ingredient in recipe.ingredients.all %}
            <li>{{ ingredient.ingredient.name }}: {{ ingredient.quantity }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'ledger:recipe_list' %}">Back to Recipe List</a>
{% endblock %}

ledger/templates/ledger/recipe_list.html
<!-- templates/ledger/recipe_list.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe List{% endblock %}
{% block content %}
	<h2>Recipe List</h2>
	<h3>Please see the recipes below:</h3>
	{% for item in recipes %}
		<li>
			<a href="{% url 'ledger:recipe_detail' pk=item.pk %}">{{ item.name }}</a>
		</li>
	{% endfor %}
{% endblock %}